OpenAIKey="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"
AzureOpenAiEndpoint = "https://cognidata.openai.azure.com/"
AzureOpenAiKey = "3sXbp2pMR6wgu0hCGxQHoxB4uADGpGtYBycbYH30jswvjBaFcvoLJQQJ99AKACYeBjFXJ3w3AAABACOG8T9Y"
AzureOpenAiVersion = "2024-08-01-preview"
AzureDeploymentName='cognidata-gpt-4o'